namespace:
  name: staging

service:
  type: ClusterIP
  port: 5111
  targetport: 3111
  protocol: TCP

deployment:
        replicaCount: 3
        image: ksaurabh/techtrends
        tag: latest
        pullpolicy: Always
        livenessProbe:
          path: /healthz
        readinessProbe:
          path: /healthz
        containerPort: 3111
        resources:
          requests:
            memory: 90Mi
            cpu: 300m        
          limits:
            memory: 128Mi
            cpu: 500m       
