namespace:
  name: sandbox

service:
  type: ClusterIP
  port: 4111
  targetport: 3111
  protocol: TCP

deployment:
        replicaCount: 1
        image: ksaurabh/techtrends
        tag: latest
        pullpolicy: IfNotPresent
        livenessProbe:
          path: /healthz
        readinessProbe:
          path: /healthz
        containerPort: 3111
        resources:
          requests:
            memory: 64Mi
            cpu: 250m        
          limits:
            memory: 128Mi
            cpu: 500m       
